-- Baseline schema captured from the live Heroku Postgres DB on 2026-05-28.
-- Generated via `pg_dump --schema-only --no-owner --no-privileges --no-comments`
-- and then hand-trimmed to drop Heroku-platform-specific objects (_heroku /
-- heroku_ext schemas, event triggers, pg_stat_statements extension) and psql
-- meta-commands (\restrict / \unrestrict) that don't apply over JDBC.
--
-- On the existing Heroku DB this file is NOT executed — Flyway is configured
-- with baseline-on-migrate=true / baseline-version=1, so it just marks V1 as
-- already-applied. On a fresh local DB, this file creates the schema from
-- scratch.

--
-- Tables (public schema)
--

CREATE TABLE public.game (
    id bigint NOT NULL,
    date timestamp without time zone,
    field character varying(255),
    opponent character varying(255),
    opponent_score integer,
    score integer,
    was_home boolean,
    team_league_id bigint NOT NULL
);

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.league (
    id bigint NOT NULL,
    name character varying(255),
    season character varying(255)
);

ALTER TABLE public.league ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.league_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.player (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- NOTE: `stat` is a vestigial table from an earlier schema iteration. No entity
-- references it; the active stat-per-game table is `stat_line`. Preserved here
-- to keep V1 a faithful snapshot of prod.
CREATE TABLE public.stat (
    id bigint NOT NULL,
    base_on_balls integer,
    batting_order integer,
    doubles integer,
    foul_outs integer,
    ground_into_double_plays integer,
    home_run_for_outs integer,
    home_runs integer,
    left_on_base integer,
    plate_appearances integer,
    runs integer,
    runs_batted_in integer,
    sacrifices integer,
    singles integer,
    strikeouts integer,
    triples integer,
    game_id bigint NOT NULL,
    team_league_player_id bigint NOT NULL
);

ALTER TABLE public.stat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.stat_line (
    id bigint NOT NULL,
    base_on_balls integer,
    batting_order integer,
    doubles integer,
    foul_outs integer,
    ground_into_double_plays integer,
    home_run_for_outs integer,
    home_runs integer,
    left_on_base integer,
    plate_appearances integer,
    runs integer,
    runs_batted_in integer,
    sacrifices integer,
    singles integer,
    strikeouts integer,
    triples integer,
    game_id bigint NOT NULL,
    team_league_player_id bigint NOT NULL
);

ALTER TABLE public.stat_line ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stat_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team_league (
    id bigint NOT NULL,
    league_id bigint NOT NULL,
    team_id bigint NOT NULL
);

ALTER TABLE public.team_league ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_league_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team_league_player (
    id bigint NOT NULL,
    player_id bigint NOT NULL,
    team_league_id bigint NOT NULL
);

ALTER TABLE public.team_league_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_league_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary key constraints
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.league
    ADD CONSTRAINT league_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.stat
    ADD CONSTRAINT stat_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.stat_line
    ADD CONSTRAINT stat_line_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_league
    ADD CONSTRAINT team_league_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_league_player
    ADD CONSTRAINT team_league_player_pkey PRIMARY KEY (id);

--
-- Foreign key constraints (names preserved from the original prod schema so
-- this file matches what's actually in Heroku — the `fk*` hashes were
-- auto-generated by Hibernate on the original ddl-auto=create run).
--

ALTER TABLE public.team_league_player ADD CONSTRAINT fk1taeqjirp15scylnak7ttq1ta FOREIGN KEY (team_league_id) REFERENCES public.team_league(id);
ALTER TABLE public.team_league_player ADD CONSTRAINT fkhabrhf1w6n25ivdnp66ggtskk FOREIGN KEY (player_id) REFERENCES public.player(id);
ALTER TABLE public.team_league ADD CONSTRAINT fk238w6qlbvsnisbuusdhp3emcq FOREIGN KEY (team_id) REFERENCES public.team(id);
ALTER TABLE public.team_league ADD CONSTRAINT fkfmgyyhxg97qcvnjjgm3ecttuh FOREIGN KEY (league_id) REFERENCES public.league(id);
ALTER TABLE public.game ADD CONSTRAINT fk9oikwx94igimo0j8fj25qx989 FOREIGN KEY (team_league_id) REFERENCES public.team_league(id);
ALTER TABLE public.stat_line ADD CONSTRAINT fkg8aikhl7yb5obxi9qafkw3trm FOREIGN KEY (game_id) REFERENCES public.game(id);
ALTER TABLE public.stat_line ADD CONSTRAINT fki77bo98gs6aqqd325jbc7b46m FOREIGN KEY (team_league_player_id) REFERENCES public.team_league_player(id);
